### ISSUE TITLE
Dataset not found

### ISSUE THREAD

**Issue by PradeepYLN** [AI4RS/MineNetCD#2]
@EricYu97  Thank you for your work. Could you please share the dataset?

**Comment by EricYu97** [comment]
Hi, @PradeepYLN , we have released the MineNetCD on our Huggingface page, which is a ready-to-use version and we have put the [link](https://huggingface.co/datasets/HZDR-FWGEL/MineNetCD256) in the arxiv paper. The full version of the dataset will be released after the paper is accepted. 

Thank you for your interest in our work!

**Comment by PradeepYLN** [comment]
Thanks a lot @EricYu97
